[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
rage = "rage9dQeAYhkEhpXwFcrqwikW81dMXdGNY77jdrSmnq"

[programs.localnet]
rage = "rage9dQeAYhkEhpXwFcrqwikW81dMXdGNY77jdrSmnq"

[programs.mainnet]
rage = "rage9dQeAYhkEhpXwFcrqwikW81dMXdGNY77jdrSmnq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm run jest src/__tests__/initialize.test.ts"

[test]
startup_wait = 12000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "CPMMoo8L3F4NbTegBCKVNunggL7H1ZpdTHKxQB5qKP1C"

[[test.validator.clone]]
address = "DNXgeM9EiiaAbaWvwjHj9fQQLAX5ZsfHyvmYUNRAdNC8"

[[test.validator.clone]]
address = "D4FPEruKEHrG5TenZ2mpDGEfu1iUvTiqBxvpU8HLBvC2"
